name: Daily Commit

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Make a change
      run: |
        date >> update.log
        git config --global user.email "domgolab@gmail.com"
        git config --global user.name "siwanetzu"
        git add .
        git commit -m "Automated commit"
        git push
